package acac

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Emit renders a Manifest as deterministic YAML: fixed key order, pre-sorted
// lists (the builder's responsibility), explicit scalar tags, LF endings,
// 2-space indent, scaffold markers as comments. Same Manifest → identical
// bytes, on every platform.
func Emit(m Manifest) ([]byte, error) {
	doc := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{buildRoot(m)}}
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("acac: emit manifest: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("acac: emit manifest: %w", err)
	}
	return buf.Bytes(), nil
}

// --- node constructors -------------------------------------------------

func keyNode(name string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: name}
}

func strNode(v string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: v}
}

func boolNode(v bool) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: fmt.Sprintf("%t", v)}
}

func intNode(v int) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: fmt.Sprintf("%d", v)}
}

func mappingNode(kv ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode, Content: kv}
}

func seqNode(items ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode, Content: items}
}

// flowStrings renders a string list inline ([a, b, c]).
func flowStrings(items []string) *yaml.Node {
	n := &yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle}
	for _, s := range items {
		n.Content = append(n.Content, strNode(s))
	}
	return n
}

// flowFacts renders a facts map inline with sorted keys.
func flowFacts(facts map[string]string) *yaml.Node {
	keys := make([]string, 0, len(facts))
	for k := range facts {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	n := &yaml.Node{Kind: yaml.MappingNode, Style: yaml.FlowStyle}
	for _, k := range keys {
		n.Content = append(n.Content, keyNode(k), strNode(facts[k]))
	}
	return n
}

// --- document sections --------------------------------------------------

func buildRoot(m Manifest) *yaml.Node {
	root := mappingNode(
		keyNode("schema_version"), strNode(SchemaVersion),
		keyNode("metadata"), buildMetadata(m.Metadata),
	)
	root.HeadComment = "Agent Format manifest generated by Trustabl.\n" +
		"Auto-derived fields come from a read-only scan of the repository; values\n" +
		"marked 'trustabl:' need human attention before deployment.\n" +
		"Schema: https://agentformat.org/schema/1.0/agentformat-schema.json"

	ifaceKey := keyNode("interface")
	ifaceKey.HeadComment = interfaceComment(m.Interface)
	root.Content = append(root.Content, ifaceKey, buildInterface())

	if m.Memory != nil {
		root.Content = append(root.Content,
			keyNode("memory"), mappingNode(keyNode("required"), boolNode(m.Memory.Required)))
	}

	root.Content = append(root.Content, keyNode("constraints"), buildConstraints(m.Constraints))
	root.Content = append(root.Content, keyNode("action_space"), buildActionSpace(m.ActionSpace))
	root.Content = append(root.Content, keyNode("execution_policy"), buildExecutionPolicy(m.ExecutionPolicy))
	root.Content = append(root.Content, keyNode("x-trustabl"), buildXTrustablNode(m.XTrustabl))
	return root
}

func buildMetadata(md Metadata) *yaml.Node {
	name := strNode(md.Name)
	if md.NameScaffolded {
		name.LineComment = MarkerNeedsHuman + " — derived from the constructor class, not a name"
	}
	desc := strNode(md.Description)
	if md.DescScaffolded {
		desc.LineComment = MarkerNeedsHuman
	}
	version := strNode(md.Version)
	version.LineComment = MarkerNeedsHuman + " — version this agent deliberately"
	return mappingNode(
		keyNode("name"), name,
		keyNode("id"), strNode(md.ID),
		keyNode("description"), desc,
		keyNode("version"), version,
	)
}

func interfaceComment(iface Interface) string {
	c := MarkerNeedsHuman + " — the engine cannot derive the agent's I/O contract;\n" +
		"replace the permissive object schemas with the real input/output shapes."
	if len(iface.ParamHints) > 0 {
		c += "\nTool signatures observed (hints): " + strings.Join(iface.ParamHints, "; ")
	}
	return c
}

func buildInterface() *yaml.Node {
	permissive := func() *yaml.Node {
		return mappingNode(keyNode("type"), strNode("object"))
	}
	return mappingNode(
		keyNode("input"), permissive(),
		keyNode("output"), permissive(),
	)
}

func buildConstraints(c Constraints) *yaml.Node {
	budget := &yaml.Node{Kind: yaml.MappingNode, Style: yaml.FlowStyle}
	budget.LineComment = MarkerNeedsHuman + " — set max_token_usage / max_duration_seconds"
	limits := &yaml.Node{Kind: yaml.MappingNode, Style: yaml.FlowStyle}
	limits.LineComment = MarkerNeedsHuman + " — set max_llm_calls / max_tool_calls / max_delegation_depth"
	gov := &yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle}
	gov.LineComment = MarkerNeedsHuman + " — reference org governance policies, if any"
	return mappingNode(
		keyNode("tighten_only_invariant"), boolNode(c.TightenOnlyInvariant),
		keyNode("budget"), budget,
		keyNode("limits"), limits,
		keyNode("governance_policies"), gov,
	)
}

func buildActionSpace(as ActionSpace) *yaml.Node {
	out := mappingNode()

	tools := seqNode()
	for _, t := range as.LocalTools {
		item := mappingNode(keyNode("alias"), strNode(t.Alias), keyNode("name"), strNode(t.Name))
		if t.Description != "" {
			item.Content = append(item.Content, keyNode("description"), strNode(t.Description))
		}
		if t.ApprovalSuggested {
			approval := boolNode(true)
			approval.LineComment = MarkerSuggested + " — tool shells out, writes files, or executes code"
			item.Content = append(item.Content, keyNode("approval"), approval)
		}
		if t.External {
			item.HeadComment = MarkerReview + " — tool reference did not resolve inside this repo"
		}
		tools.Content = append(tools.Content, item)
	}
	out.Content = append(out.Content, keyNode("local_tools"), tools)

	servers := seqNode()
	for _, s := range as.MCPServers {
		ref := strNode("")
		ref.LineComment = MarkerNeedsHuman + " — registry/catalog identity of this server"
		item := mappingNode(
			keyNode("alias"), strNode(s.Alias),
			keyNode("server_ref"), ref,
		)
		if s.Description != "" {
			item.Content = append(item.Content, keyNode("description"), strNode(s.Description))
		}
		allowed := flowStrings(s.AllowedTools)
		if !s.AllowedToolsDerived {
			allowed = flowStrings(nil)
			allowed.LineComment = MarkerNeedsHuman + " — not derivable from code; list the tools this server may expose"
		}
		item.Content = append(item.Content, keyNode("allowed_tools"), allowed)
		if s.External {
			item.HeadComment = MarkerReview + " — MCP server reference did not resolve inside this repo"
		}
		servers.Content = append(servers.Content, item)
	}
	out.Content = append(out.Content, keyNode("mcp_servers"), servers)

	agents := seqNode()
	for _, a := range as.LocalAgents {
		item := mappingNode(
			keyNode("alias"), strNode(a.Alias),
			keyNode("source_type"), strNode(a.SourceType),
			keyNode("source"), strNode(a.Source),
		)
		if a.Description != "" {
			item.Content = append(item.Content, keyNode("description"), strNode(a.Description))
		}
		if a.Review {
			item.HeadComment = MarkerReview + " — handoff target is defined in source code, not a manifest"
		}
		agents.Content = append(agents.Content, item)
	}
	out.Content = append(out.Content, keyNode("local_agents"), agents)

	return out
}

func buildExecutionPolicy(ep ExecutionPolicy) *yaml.Node {
	instructions := strNode(ep.Instructions)
	if ep.InstructionsScaffolded {
		instructions.LineComment = MarkerNeedsHuman
	}
	model := strNode(ep.Model)
	if ep.ModelScaffolded {
		model.LineComment = MarkerNeedsHuman
	}
	return mappingNode(
		keyNode("id"), strNode(ep.ID),
		keyNode("config"), mappingNode(
			keyNode("instructions"), instructions,
			keyNode("model"), model,
		),
	)
}

func buildXTrustablNode(x XTrustabl) *yaml.Node {
	out := mappingNode(
		keyNode("spec_version"), strNode(x.SpecVersion),
		keyNode("engine_version"), strNode(x.EngineVersion),
		keyNode("rules_version"), strNode(x.RulesVersion),
		keyNode("scan_id"), strNode(x.ScanID),
	)
	if x.GeneratedAt != "" {
		ts := strNode(x.GeneratedAt)
		ts.LineComment = "informational; never part of scan_id"
		out.Content = append(out.Content, keyNode("generated_at"), ts)
	}
	score := intNode(x.Score100)
	score.LineComment = "informational in v0.x — thresholds pending calibration"
	out.Content = append(out.Content,
		keyNode("agent"), strNode(x.Agent),
		keyNode("deployment_readiness"), strNode(string(x.Readiness)),
		keyNode("reliability_score"), score,
	)

	surfaces := seqNode()
	for _, s := range x.Surfaces {
		item := mappingNode(
			keyNode("kind"), strNode(s.Kind),
			keyNode("ref"), strNode(s.Ref),
			keyNode("score"), intNode(s.Score),
		)
		if len(s.Facts) > 0 {
			item.Content = append(item.Content, keyNode("facts"), flowFacts(s.Facts))
		}
		surfaces.Content = append(surfaces.Content, item)
	}
	out.Content = append(out.Content, keyNode("surfaces"), surfaces)

	findings := seqNode()
	for _, f := range x.Findings {
		item := mappingNode(
			keyNode("id"), strNode(f.ID),
			keyNode("scope"), strNode(f.Scope),
		)
		if f.Ref != "" {
			item.Content = append(item.Content, keyNode("ref"), strNode(f.Ref))
		}
		item.Content = append(item.Content,
			keyNode("severity"), strNode(f.Severity),
			keyNode("message"), strNode(f.Message),
		)
		if f.Fix != "" {
			item.Content = append(item.Content, keyNode("fix"), strNode(f.Fix))
		}
		if len(f.OWASP) > 0 {
			item.Content = append(item.Content, keyNode("owasp"), flowStrings(f.OWASP))
		}
		findings.Content = append(findings.Content, item)
	}
	out.Content = append(out.Content, keyNode("findings"), findings)

	if len(x.Skills) > 0 {
		skills := seqNode()
		for _, s := range x.Skills {
			skills.Content = append(skills.Content, mappingNode(
				keyNode("name"), strNode(s.Name),
				keyNode("tool_grants"), flowStrings(s.ToolGrants),
				keyNode("model_invocable"), boolNode(s.ModelInvocable),
			))
		}
		out.Content = append(out.Content, keyNode("skills"), skills)
	}

	if len(x.HostedTools) > 0 {
		out.Content = append(out.Content, keyNode("hosted_tools"), flowStrings(x.HostedTools))
	}

	cov := mappingNode(
		keyNode("sdks_detected"), flowStrings(x.Coverage.SDKsDetected),
		keyNode("unaudited"), flowStrings(x.Coverage.Unaudited),
		keyNode("dependencies"), mappingNode(
			keyNode("count"), intNode(x.Coverage.DepCount),
			keyNode("manifests"), flowStrings(x.Coverage.DepManifests),
		),
	)
	out.Content = append(out.Content, keyNode("coverage"), cov)

	if len(x.Vulnerabilities) > 0 {
		vulns := seqNode()
		for _, v := range x.Vulnerabilities {
			item := mappingNode(
				keyNode("id"), strNode(v.ID),
				keyNode("package"), strNode(v.Package),
				keyNode("severity"), strNode(v.Severity),
			)
			if v.FixedVersion != "" {
				item.Content = append(item.Content, keyNode("fixed_version"), strNode(v.FixedVersion))
			}
			vulns.Content = append(vulns.Content, item)
		}
		out.Content = append(out.Content, keyNode("vulnerabilities"), vulns)
	}

	return out
}
