package acac

import (
	"bytes"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// EmitOpenShellPolicy renders a policy deterministically, on the same yaml.v3
// node infrastructure as the manifest emitter: fixed key order, pre-sorted
// lists, explicit scalar tags, marker comments, LF endings.
func EmitOpenShellPolicy(p OpenShellPolicy) ([]byte, error) {
	// landlock.compatibility defaults to best_effort (degrade on kernels without
	// Landlock); hard_requirement fails closed instead — a deployment choice.
	compat := strNode("best_effort")
	compat.LineComment = "alternative: hard_requirement fails closed when the kernel lacks Landlock"

	// run_as_user/group are required to be exactly "sandbox" by OpenShell; the
	// BYOC note records the one documented exception so the value is not mistaken
	// for a freely-editable field.
	processKey := keyNode("process")
	processKey.HeadComment = "run_as_user/group must be 'sandbox' (OpenShell-enforced).\n" +
		"BYOC note: `sandbox create --from <image>` clears these because a custom\n" +
		"image may lack a 'sandbox' user."

	root := mappingNode(
		keyNode("version"), intNode(1),
		keyNode("filesystem_policy"), mappingNode(
			keyNode("include_workdir"), boolNode(true),
			keyNode("read_only"), flowStrings(p.ReadOnly),
			keyNode("read_write"), flowStrings(p.ReadWrite),
		),
		keyNode("landlock"), mappingNode(
			keyNode("compatibility"), compat,
		),
		processKey, mappingNode(
			keyNode("run_as_user"), strNode(p.RunAsUser),
			keyNode("run_as_group"), strNode(p.RunAsGroup),
		),
	)
	root.HeadComment = "OpenShell sandbox policy generated by Trustabl from a read-only scan.\n" +
		"Self-contained: suitable for sandbox creation and `openshell policy set`.\n" +
		"Lifecycle: filesystem_policy and process are LOCKED at sandbox creation;\n" +
		"only network_policies hot-reload. Values marked 'trustabl:' need human\n" +
		"attention before use."

	netKey := keyNode("network_policies")
	if len(p.ReviewNotes) > 0 {
		notes := make([]string, 0, len(p.ReviewNotes))
		for _, n := range p.ReviewNotes {
			notes = append(notes, MarkerReview+" — "+n)
		}
		netKey.HeadComment = strings.Join(notes, "\n")
	}

	netVal := &yaml.Node{Kind: yaml.MappingNode}
	if len(p.Network) == 0 {
		netVal.Style = yaml.FlowStyle // {} — explicit empty block
	}
	for _, np := range p.Network {
		entry := mappingNode(
			keyNode("name"), strNode(np.Name),
		)
		endpoints := seqNode()
		for _, ep := range np.Endpoints {
			epNode := mappingNode()
			if ep.Host != "" {
				epNode.Content = append(epNode.Content, keyNode("host"), strNode(ep.Host))
			}
			epNode.Content = append(epNode.Content, keyNode("port"), intNode(ep.Port))
			if len(ep.AllowedIPs) > 0 {
				epNode.Content = append(epNode.Content, keyNode("allowed_ips"), flowStrings(ep.AllowedIPs))
			}
			epNode.Content = append(epNode.Content,
				keyNode("protocol"), strNode("rest"),
				keyNode("enforcement"), strNode("enforce"),
			)
			if ep.Marker != "" {
				epNode.HeadComment = MarkerReview + " — " + ep.Marker
			}
			if len(ep.Rules) > 0 {
				// Fine-grained L7 rules (mutually exclusive with access): one
				// allow:{method, path} entry per captured (method, path).
				rulesSeq := seqNode()
				for _, r := range ep.Rules {
					rulesSeq.Content = append(rulesSeq.Content, mappingNode(
						keyNode("allow"), mappingNode(
							keyNode("method"), strNode(r.Method),
							keyNode("path"), strNode(r.Path),
						),
					))
				}
				epNode.Content = append(epNode.Content, keyNode("rules"), rulesSeq)
			} else {
				// Coarse access preset derived from the tool's HTTP verbs
				// (read-only / read-write / full); default read-only when unset.
				access := ep.Access
				if access == "" {
					access = "read-only"
				}
				epNode.Content = append(epNode.Content, keyNode("access"), strNode(access))
			}
			endpoints.Content = append(endpoints.Content, epNode)
		}
		entry.Content = append(entry.Content, keyNode("endpoints"), endpoints)
		if len(np.Binaries) > 0 {
			bins := seqNode()
			for _, b := range np.Binaries {
				pathVal := strNode(b)
				pathVal.LineComment = MarkerReview + " — confirm the interpreter path inside the sandbox"
				bins.Content = append(bins.Content, mappingNode(keyNode("path"), pathVal))
			}
			entry.Content = append(entry.Content, keyNode("binaries"), bins)
		}
		netVal.Content = append(netVal.Content, keyNode(np.Key), entry)
	}
	root.Content = append(root.Content, netKey, netVal)

	doc := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("acac: emit openshell policy: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("acac: emit openshell policy: %w", err)
	}
	return buf.Bytes(), nil
}
