package acac

// Spike for ACaC Stage 1 work item 0: prove that the yaml.v3 Node API can
// emit a nested, comment-bearing document deterministically. The real
// emitter (emit.go) builds on the patterns proven here. The exit criterion
// is byte-identical output across repeated encodes, LF-only line endings,
// and correctly placed HeadComment/LineComment markers at every nesting
// depth the manifest needs (top-level keys, nested mapping keys, sequence
// items, scalars inside sequence items).

import (
	"bytes"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func scalarNode(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Value: value}
}

func keyNode(name string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Value: name}
}

// buildSpikeDoc constructs a document exercising every comment placement the
// manifest emitter needs.
func buildSpikeDoc() *yaml.Node {
	// metadata.version with a line-comment marker on the value.
	version := scalarNode("0.1.0")
	version.LineComment = "trustabl: needs-human-input"

	// A nested mapping whose key carries a head comment.
	inputKey := keyNode("input")
	inputKey.HeadComment = "trustabl: needs-human-input — replace the permissive schema"
	inputVal := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
		keyNode("type"), scalarNode("object"),
	}}

	iface := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
		inputKey, inputVal,
		keyNode("output"), &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
			keyNode("type"), scalarNode("object"),
		}},
	}}

	// A sequence of mappings; one item carries a head comment, one scalar
	// inside an item carries a line comment.
	approval := scalarNode("true")
	approval.Tag = "!!bool"
	approval.LineComment = "trustabl: suggested — confirm"

	tool1 := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
		keyNode("alias"), scalarNode("run_shell"),
		keyNode("approval"), approval,
	}}
	tool2 := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
		keyNode("alias"), scalarNode("search_web"),
	}}
	tool2.HeadComment = "trustabl: review — handoff target defined in code"

	tools := &yaml.Node{Kind: yaml.SequenceNode, Content: []*yaml.Node{tool1, tool2}}

	root := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
		keyNode("schema_version"), scalarNode("1.0.0"),
		keyNode("metadata"), &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
			keyNode("name"), scalarNode("Main Agent"),
			keyNode("version"), version,
		}},
		keyNode("interface"), iface,
		keyNode("local_tools"), tools,
	}}
	root.HeadComment = "Generated by Trustabl. Do not edit derived fields by hand."

	return &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}
}

func encodeSpike(t *testing.T) []byte {
	t.Helper()
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(buildSpikeDoc()); err != nil {
		t.Fatalf("encode: %v", err)
	}
	if err := enc.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}
	return buf.Bytes()
}

func TestSpikeCommentedEmissionIsDeterministic(t *testing.T) {
	first := encodeSpike(t)
	for i := 0; i < 10; i++ {
		if next := encodeSpike(t); !bytes.Equal(first, next) {
			t.Fatalf("encode run %d differs from first run:\nfirst:\n%s\nrun:\n%s", i+2, first, next)
		}
	}
}

func TestSpikeCommentPlacementAndLineEndings(t *testing.T) {
	out := string(encodeSpike(t))

	if strings.Contains(out, "\r") {
		t.Fatal("output contains CR; emitter must be LF-only")
	}

	for _, want := range []string{
		"# Generated by Trustabl. Do not edit derived fields by hand.",
		"version: 0.1.0 # trustabl: needs-human-input",
		"# trustabl: needs-human-input — replace the permissive schema",
		"approval: true # trustabl: suggested — confirm",
		"# trustabl: review — handoff target defined in code",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing expected emission %q in:\n%s", want, out)
		}
	}

	// The nested-key head comment must sit directly above its key at the
	// key's own indentation, not float to the parent.
	idx := strings.Index(out, "# trustabl: needs-human-input — replace the permissive schema")
	if idx < 0 {
		t.Fatal("head comment missing")
	}
	rest := out[idx:]
	lines := strings.SplitN(rest, "\n", 3)
	if len(lines) < 2 || !strings.HasPrefix(strings.TrimSpace(lines[1]), "input:") {
		t.Errorf("head comment is not directly above its key; following line: %q", lines[1])
	}
}
