// Package generation emits the orange artifacts of architecture §4: the
// Pre/PostToolUse hook files and the OpenShell sandbox policy YAML.
//
// Design rule: generators are deterministic and stable. Same findings →
// byte-identical output. This is what makes diff review (architecture §2,
// Review & Export) meaningful and what lets users re-run a scan in CI without
// chasing spurious diffs.
package generation

import (
	"fmt"
	"sort"
	"strings"

	"github.com/trustabl/karenctl/internal/models"
)

// GenerateHooks emits two artifacts: hooks/pretooluse_validate.py and
// hooks/posttooluse_log.py.
//
// IMPORTANT: the exact PreToolUse/PostToolUse contract in the Claude Agent SDK
// is still moving (the architecture doc was written against a pre-1.0 SDK).
// The generated files use a contract that's plausible against the public SDK
// shape but MUST be reviewed when the SDK signature stabilizes. The generator
// is intentionally narrow — it emits validators per tool and a dispatch
// function. Changing the SDK contract changes one place (this file), not the
// per-tool logic.
func GenerateHooks(findings []models.Finding) []models.GeneratedArtifact {
	// Group findings by tool. Sort tools and findings deterministically so the
	// output is byte-stable.
	byTool := groupByTool(findings)
	toolNames := make([]string, 0, len(byTool))
	for name := range byTool {
		toolNames = append(toolNames, name)
	}
	sort.Strings(toolNames)

	pre := buildPreToolUse(byTool, toolNames)
	post := buildPostToolUse(toolNames)

	rationale := fmt.Sprintf(
		"Generated from %d hook-eligible findings across %d tools. Re-runs are byte-stable.",
		len(findings), len(toolNames),
	)

	return []models.GeneratedArtifact{
		{
			RelativePath: "hooks/pretooluse_validate.py",
			Contents:     pre,
			Category:     models.CategoryClaudeSDK,
			Rationale:    rationale,
		},
		{
			RelativePath: "hooks/posttooluse_log.py",
			Contents:     post,
			Category:     models.CategoryClaudeSDK,
			Rationale:    "Structured logging hook. Phase 2 will route these events to OTEL.",
		},
	}
}

func groupByTool(findings []models.Finding) map[string][]models.Finding {
	out := map[string][]models.Finding{}
	for _, f := range findings {
		// Only hook-eligible findings: those whose fix_hints opt into a hook.
		if !isHookEligible(f) {
			continue
		}
		out[f.ToolName] = append(out[f.ToolName], f)
	}
	for k := range out {
		sort.SliceStable(out[k], func(i, j int) bool {
			return out[k][i].RuleID < out[k][j].RuleID
		})
	}
	return out
}

func isHookEligible(f models.Finding) bool {
	if v, ok := f.FixHints["hook"]; ok {
		if s, ok := v.(string); ok && s != "" {
			return true
		}
	}
	// Sensible defaults: CSDK rules with concrete fix hints get a hook;
	// OSH rules go to the policy generator instead.
	if f.Category != models.CategoryClaudeSDK {
		return false
	}
	switch f.RuleID {
	case "CSDK-003", "CSDK-004", "CSDK-006":
		return true
	}
	return false
}

// ────────────────────────────────────────────────────────────────────────────
// PreToolUse generation
// ────────────────────────────────────────────────────────────────────────────

const preHeader = `# Generated by karenctl. DO NOT EDIT — re-run ` + "`karenctl scan --apply`" + ` instead.
#
# PreToolUse validator. The Claude Agent SDK invokes this before every tool call,
# passing the tool name and the planned argument dict. The hook can:
#   - mutate args (e.g. inject a timeout)
#   - raise to reject the call
#   - return args unchanged to accept
#
# Contract note: the SDK signature is pre-1.0 and may change. If it does, edit
# the dispatch entry point below; the per-tool validators are isolated.

from __future__ import annotations

from pathlib import Path
from typing import Any
import uuid


class ToolValidationError(Exception):
    """Raised when a tool call must be rejected outright."""


def validate(tool_name: str, args: dict[str, Any]) -> dict[str, Any]:
    """Dispatch entry point. Returns the (possibly mutated) args."""
    handler = _DISPATCH.get(tool_name)
    if handler is None:
        return args
    return handler(args)

`

func buildPreToolUse(byTool map[string][]models.Finding, toolNames []string) string {
	var b strings.Builder
	b.WriteString(preHeader)

	// Per-tool validator functions.
	for _, name := range toolNames {
		findings := byTool[name]
		if len(findings) == 0 {
			continue
		}
		b.WriteString(buildValidatorFunc(name, findings))
		b.WriteString("\n")
	}

	// Dispatch table.
	b.WriteString("_DISPATCH = {\n")
	for _, name := range toolNames {
		if len(byTool[name]) == 0 {
			continue
		}
		fmt.Fprintf(&b, "    %q: _validate_%s,\n", name, sanitize(name))
	}
	b.WriteString("}\n")
	return b.String()
}

func buildValidatorFunc(toolName string, findings []models.Finding) string {
	var b strings.Builder
	fmt.Fprintf(&b, "def _validate_%s(args: dict[str, Any]) -> dict[str, Any]:\n", sanitize(toolName))
	fmt.Fprintf(&b, "    \"\"\"Generated from %d finding(s): %s\"\"\"\n",
		len(findings), joinRuleIDs(findings))
	wroteAny := false
	for _, f := range findings {
		stanza := stanzaForFinding(f)
		if stanza == "" {
			continue
		}
		// Comment with the rule id and one-line rationale.
		fmt.Fprintf(&b, "    # %s — %s\n", f.RuleID, f.Title)
		b.WriteString(stanza)
		wroteAny = true
	}
	if !wroteAny {
		b.WriteString("    # No actionable hook stanzas; this function is a placeholder.\n")
	}
	b.WriteString("    return args\n")
	return b.String()
}

// stanzaForFinding returns the Python body lines (already indented 4 spaces)
// that implement the fix for a given finding. Returns "" if the finding has
// no hook-level remediation.
func stanzaForFinding(f models.Finding) string {
	switch f.RuleID {
	case "CSDK-003":
		// Inject a default timeout if not specified.
		return "    args.setdefault(\"timeout\", 15)\n"

	case "CSDK-004":
		// Resolve any path-shaped arg and assert containment in ./data.
		// The allowed root is a placeholder; surfaced as a TODO so the
		// user adapts to their layout before committing.
		return strings.Join([]string{
			"    _ALLOWED_ROOT = Path(\"./data\").resolve()  # TODO: confirm correct root",
			"    for _key in (\"path\", \"file_path\", \"filename\", \"directory\", \"dir\"):",
			"        if _key in args and args[_key] is not None:",
			"            _p = Path(args[_key]).resolve()",
			"            if not str(_p).startswith(str(_ALLOWED_ROOT)):",
			"                raise ToolValidationError(",
			"                    f\"{_key}={_p!s} escapes allowed root {_ALLOWED_ROOT!s}\"",
			"                )",
			"            args[_key] = str(_p)",
			"",
		}, "\n")

	case "CSDK-006":
		// Inject an idempotency key if not supplied.
		return strings.Join([]string{
			"    if \"idempotency_key\" not in args or not args[\"idempotency_key\"]:",
			"        args[\"idempotency_key\"] = f\"karenctl-{uuid.uuid4()}\"",
			"",
		}, "\n")
	}
	return ""
}

// ────────────────────────────────────────────────────────────────────────────
// PostToolUse generation
// ────────────────────────────────────────────────────────────────────────────

func buildPostToolUse(toolNames []string) string {
	var b strings.Builder
	b.WriteString(`# Generated by karenctl. DO NOT EDIT.
#
# PostToolUse hook. Receives the tool name, the args that were ultimately
# invoked, the raw result, and the wall-clock duration. Default behavior is
# structured logging; Phase 2 will swap this for OTEL span emission.

from __future__ import annotations

import json
import logging
import time
from typing import Any

_LOG = logging.getLogger("karenctl.tool")


def log(tool_name: str, args: dict[str, Any], result: Any, duration_ms: float) -> None:
    payload = {
        "ts": time.time(),
        "tool": tool_name,
        "duration_ms": round(duration_ms, 2),
        "args_keys": sorted(list(args.keys())),
        "result_type": type(result).__name__,
    }
    _LOG.info(json.dumps(payload))
`)
	if len(toolNames) > 0 {
		b.WriteString("\n\n# Known tools this hook is configured for:\n")
		for _, name := range toolNames {
			fmt.Fprintf(&b, "#   - %s\n", name)
		}
	}
	return b.String()
}

// ────────────────────────────────────────────────────────────────────────────
// helpers
// ────────────────────────────────────────────────────────────────────────────

func sanitize(name string) string {
	// Python identifier: replace non-[A-Za-z0-9_] with underscore, prefix if it
	// starts with a digit. Don't bother with keyword collisions — we're
	// always prefixed with `_validate_`.
	var b strings.Builder
	for i, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r == '_':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			if i == 0 {
				b.WriteRune('_')
			}
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	if b.Len() == 0 {
		return "tool"
	}
	return b.String()
}

func joinRuleIDs(findings []models.Finding) string {
	ids := make([]string, len(findings))
	for i, f := range findings {
		ids[i] = f.RuleID
	}
	return strings.Join(ids, ", ")
}
